default: &default
  development:
  adapter: postgresql
  encoding: unicode
  database: music_brainz
  pool: 5
  username: postgres
  password: postgres123

test:
  adapter: postgresql
  encoding: unicode
  database: music_brainz
  pool: 5
  username: postgres
  password: postgres123