---
__ArbitratorConfiguration: !ruby/object:Nanotek::ClassDefinition
  name: __ArbitratorConfiguration
  path: ROOT
  properties:
  - !ruby/struct
    with: outstandingtaskstotal
  - !ruby/struct
    with: permanentsubscriptionsperuser
  - !ruby/struct
    with: permanentsubscriptionstotal
  - !ruby/struct
    with: pollinginstructionsperuser
  - !ruby/struct
    with: pollinginstructionstotal
  - !ruby/struct
    with: pollingmemoryperuser
  - !ruby/struct
    with: pollingmemorytotal
  - !ruby/struct
    with: quotaretrycount
  - !ruby/struct
    with: quotaretrywaitinterval
  - !ruby/struct
    with: taskthreadsperuser
  - !ruby/struct
    with: taskthreadstotal
  - !ruby/struct
    with: temporarysubscriptionsperuser
  - !ruby/struct
    with: temporarysubscriptionstotal
  - !ruby/struct
    with: totalcachedisk
  - !ruby/struct
    with: totalcachediskpertask
  - !ruby/struct
    with: totalcachediskperuser
  - !ruby/struct
    with: totalcachememory
  - !ruby/struct
    with: totalcachememorypertask
  - !ruby/struct
    with: totalcachememoryperuser
  - !ruby/struct
    with: totalusers
  - !ruby/struct
    with: __class
  - !ruby/struct
    with: __derivation
  - !ruby/struct
    with: __dynasty
  - !ruby/struct
    with: __genus
  - !ruby/struct
    with: __namespace
  - !ruby/struct
    with: __path
  - !ruby/struct
    with: __property_count
  - !ruby/struct
    with: __relpath
  - !ruby/struct
    with: __server
